config/routes.rb
Rails.application.routes.draw do
  resources :modalities
  resources :rooms
  resources :professionals
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/professional.rb
class Professional < ApplicationRecord
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  before_action :set_professional, only: %i[ show edit update destroy ]

  # GET /professionals or /professionals.json
  def index
    @professionals = Professional.all
  end

  # GET /professionals/1 or /professionals/1.json
  def show
  end

  # GET /professionals/new
  def new
    @professional = Professional.new
  end

  # GET /professionals/1/edit
  def edit
  end

  # POST /professionals or /professionals.json
  def create
    @professional = Professional.new(professional_params)

    respond_to do |format|
      if @professional.save
        format.html { redirect_to professional_url(@professional), notice: "Professional was successfully created." }
        format.json { render :show, status: :created, location: @professional }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @professional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professionals/1 or /professionals/1.json
  def update
    respond_to do |format|
      if @professional.update(professional_params)
        format.html { redirect_to professional_url(@professional), notice: "Professional was successfully updated." }
        format.json { render :show, status: :ok, location: @professional }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @professional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professionals/1 or /professionals/1.json
  def destroy
    @professional.destroy

    respond_to do |format|
      format.html { redirect_to professionals_url, notice: "Professional was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professional
      @professional = Professional.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def professional_params
      params.require(:professional).permit(:name, :phone, :email)
    end
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/views/professionals/_form.html.erb
<%= form_with(model: professional) do |form| %>
  <% if professional.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(professional.errors.count, "error") %> prohibited this professional from being saved:</h2>

      <ul>
        <% professional.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/professionals/_professional.html.erb
<div id="<%= dom_id professional %>">
  <p>
    <strong>Name:</strong>
    <%= professional.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= professional.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= professional.email %>
  </p>

</div>

app/views/professionals/edit.html.erb
<h1>Editing professional</h1>

<%= render "form", professional: @professional %>

<br>

<div>
  <%= link_to "Show this professional", @professional %> |
  <%= link_to "Back to professionals", professionals_path %>
</div>

app/views/professionals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Professionals</h1>

<div id="professionals">
  <% @professionals.each do |professional| %>
    <%= render professional %>
    <p>
      <%= link_to "Show this professional", professional %>
    </p>
  <% end %>
</div>

<%= link_to "New professional", new_professional_path %>

app/views/professionals/new.html.erb
<h1>New professional</h1>

<%= render "form", professional: @professional %>

<br>

<div>
  <%= link_to "Back to professionals", professionals_path %>
</div>

app/views/professionals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @professional %>

<div>
  <%= link_to "Edit this professional", edit_professional_path(@professional) %> |
  <%= link_to "Back to professionals", professionals_path %>

  <%= button_to "Destroy this professional", @professional, method: :delete %>
</div>