config/routes.rb
Rails.application.routes.draw do
  resources :modalities
  resources :rooms
  resources :professionals
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/modality.rb
class Modality < ApplicationRecord
end

app/controllers/modalities_controller.rb
class ModalitiesController < ApplicationController
  before_action :set_modality, only: %i[ show edit update destroy ]

  # GET /modalities or /modalities.json
  def index
    @modalities = Modality.all
  end

  # GET /modalities/1 or /modalities/1.json
  def show
  end

  # GET /modalities/new
  def new
    @modality = Modality.new
  end

  # GET /modalities/1/edit
  def edit
  end

  # POST /modalities or /modalities.json
  def create
    @modality = Modality.new(modality_params)

    respond_to do |format|
      if @modality.save
        format.html { redirect_to modality_url(@modality), notice: "Modality was successfully created." }
        format.json { render :show, status: :created, location: @modality }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @modality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modalities/1 or /modalities/1.json
  def update
    respond_to do |format|
      if @modality.update(modality_params)
        format.html { redirect_to modality_url(@modality), notice: "Modality was successfully updated." }
        format.json { render :show, status: :ok, location: @modality }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @modality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modalities/1 or /modalities/1.json
  def destroy
    @modality.destroy

    respond_to do |format|
      format.html { redirect_to modalities_url, notice: "Modality was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modality
      @modality = Modality.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def modality_params
      params.require(:modality).permit(:name, :description)
    end
end

app/helpers/modalities_helper.rb
module ModalitiesHelper
end

app/views/modalities/_form.html.erb
<%= form_with(model: modality) do |form| %>
  <% if modality.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(modality.errors.count, "error") %> prohibited this modality from being saved:</h2>

      <ul>
        <% modality.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/modalities/_modality.html.erb
<div id="<%= dom_id modality %>">
  <p>
    <strong>Name:</strong>
    <%= modality.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= modality.description %>
  </p>

</div>

app/views/modalities/edit.html.erb
<h1>Editing modality</h1>

<%= render "form", modality: @modality %>

<br>

<div>
  <%= link_to "Show this modality", @modality %> |
  <%= link_to "Back to modalities", modalities_path %>
</div>

app/views/modalities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Modalities</h1>

<div id="modalities">
  <% @modalities.each do |modality| %>
    <%= render modality %>
    <p>
      <%= link_to "Show this modality", modality %>
    </p>
  <% end %>
</div>

<%= link_to "New modality", new_modality_path %>

app/views/modalities/new.html.erb
<h1>New modality</h1>

<%= render "form", modality: @modality %>

<br>

<div>
  <%= link_to "Back to modalities", modalities_path %>
</div>

app/views/modalities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @modality %>

<div>
  <%= link_to "Edit this modality", edit_modality_path(@modality) %> |
  <%= link_to "Back to modalities", modalities_path %>

  <%= button_to "Destroy this modality", @modality, method: :delete %>
</div>